site_name: Test Driver
site_description: Test Site
site_author: Rick Peters
copyright: "&copy; plpteam 2011-2015"

markdown_extensions:
  - sane_lists
  - def_list
  - footnotes
  - admonition
  - smarty
  - mdx_graphviz:
     FORMAT: "svg"
     WRITE_IMGS_DIR: "documentatie/media/"
     BINARY_PATH: "/usr/bin/"
     BASE_IMG_LINK_DIR: "/media/"

#theme: readthedocs
theme: mkdocs
# override dir for default theme
theme_dir: 'plp_theme'

docs_dir: 'documentatie'
site_dir: 'nginx/site'

use_directory_urls: false

# link checking stops processing
#strict: true

#pages:
#- ['uitgangspunten.md', 'Introductie']

